# Dimensions

In [4]:
import numpy as np

In [5]:
scalar = np.array(1)
vector = np.array([1,15,14,16,18,12,20])
matrix = np.array([[1,2,3,4],[10,11,12,13],[14,15,16,18]])
tensor = np.array([[[1,2,3,4],[10,11,12,13],[14,15,16,18],[12,15,48,7]] ,[[14,12,15,17],[54,65,98,78],[3,0,45,65],[7,8,9,52]]])

In [6]:
print(scalar)
print(f'The scalar dimension is: {scalar.ndim}')

print(vector)
print(f'The vector dimension is: {vector.ndim}')

print(matrix)
print(f'The matrix dimension is: {matrix.ndim}')

print(tensor)
print(f'The tensor dimension is: {tensor.ndim}')


1
The scalar dimension is: 0
[ 1 15 14 16 18 12 20]
The vector dimension is: 1
[[ 1  2  3  4]
 [10 11 12 13]
 [14 15 16 18]]
The matrix dimension is: 2
[[[ 1  2  3  4]
  [10 11 12 13]
  [14 15 16 18]
  [12 15 48  7]]

 [[14 12 15 17]
  [54 65 98 78]
  [ 3  0 45 65]
  [ 7  8  9 52]]]
The tensor dimension is: 3


## Add or eliminate dimensions
note: in numpy and python in general axis 0 = rows, and axis 1 = columns

In [7]:
vector = np.array([1,15,14,16,18,12,20], ndmin=10) #el siguiente me devolvera el objeto con 10 dimensiones
print(vector)
print(f' {vector.ndim}')

[[[[[[[[[[ 1 15 14 16 18 12 20]]]]]]]]]]
 10


In [8]:
expandvecto=np.expand_dims(np.array([1,2,3]), axis=0) #expandar dimension en ejes
print(expandvecto)
expandvecto.ndim

[[1 2 3]]


2

In [9]:
#eliminate dimensions
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[ 1 15 14 16 18 12 20]]]]]]]]]] 10
[ 1 15 14 16 18 12 20] 1


## Challenge
1. Define a tensor at least 5 dimensions
2. add one dimension in any axis
3. delete unnecessary dimensions

In [10]:
tensor = np.array([[[1,2,3,4],[10,11,12,13],[14,15,16,18],[12,15,48,7]] ,
                    [[14,12,15,17],[54,65,98,78],[3,0,45,65],[7,8,9,52]],
                    [[85,95,65,35],[45,78,45,1200],[0,12,36,5],[45,8,7,6]]], ndmin=7)
print(tensor, tensor.ndim)

[[[[[[[   1    2    3    4]
      [  10   11   12   13]
      [  14   15   16   18]
      [  12   15   48    7]]

     [[  14   12   15   17]
      [  54   65   98   78]
      [   3    0   45   65]
      [   7    8    9   52]]

     [[  85   95   65   35]
      [  45   78   45 1200]
      [   0   12   36    5]
      [  45    8    7    6]]]]]]] 7


In [11]:
tensorexpand = np.expand_dims(tensor, axis=2)
tensorexpand.ndim

8

In [12]:
tensor2 = np.squeeze(tensor)
print(tensor2, tensor2.ndim)

[[[   1    2    3    4]
  [  10   11   12   13]
  [  14   15   16   18]
  [  12   15   48    7]]

 [[  14   12   15   17]
  [  54   65   98   78]
  [   3    0   45   65]
  [   7    8    9   52]]

 [[  85   95   65   35]
  [  45   78   45 1200]
  [   0   12   36    5]
  [  45    8    7    6]]] 3


# Arrays

In [13]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10) #generate values from 0 to 10-1
np.arange(0,10,2) #generate the values but in 2 steps

array([0, 2, 4, 6, 8])

In [17]:
np.zeros((10,10))  #me da un array de ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,100) #me genera un numero de datos qe yo quiera dentro del rango

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand()  #general valores aleatorios de 0 a 1
np.random.rand(4)  #genera array con valores alatorios 
np.random.rand(4,4) #genera array ,atrixx con valores aleatorios

array([[0.16796367, 0.39070266, 0.8781691 , 0.96049838],
       [0.80355075, 0.73278658, 0.81070055, 0.33007594],
       [0.29693293, 0.34185384, 0.12327146, 0.40327416],
       [0.77482011, 0.94868582, 0.03312648, 0.70140492]])

In [27]:
np.random.randint(1,15) #valores aleatorios entre 1 y 15
np.random.randint(1,15, (10,10)) #matrix de 10x10 con valores aleatorios entre 1 y 15

array([[ 1,  1, 10,  2,  7,  6,  5, 11,  8,  8],
       [11, 11, 11,  6,  8, 12, 12,  7, 14,  8],
       [13,  1, 12, 11, 12,  2,  5, 13,  2, 14],
       [11,  5,  7, 14, 11,  9,  1, 10, 10,  2],
       [14, 13, 12,  8,  1,  3, 11,  6, 10, 13],
       [ 4,  4,  2,  6,  5, 11,  1,  6, 14, 11],
       [ 7, 14,  6,  1, 13, 14,  2,  9,  8,  5],
       [12, 10,  8,  3, 10,  7,  7, 13,  8, 12],
       [ 2, 11,  1,  9,  1,  9,  3, 11, 13, 12],
       [13,  8, 14, 10,  6, 10, 10, 12, 10, 12]])

## Shape and reshape

In [32]:
arr = np.random.randint(1,10,(3,2))
arr

array([[9, 6],
       [8, 2],
       [9, 8]])

In [33]:
arr.shape  #muestra filas y columnas

(3, 2)

In [34]:
arr.reshape(1,6)

array([[9, 6, 8, 2, 9, 8]])

In [35]:
arr.reshape(2,3)

array([[9, 6, 8],
       [2, 9, 8]])

In [36]:
np.reshape(arr, (1,6))

array([[9, 6, 8, 2, 9, 8]])

In [37]:
arr

array([[9, 6],
       [8, 2],
       [9, 8]])

In [38]:
np.reshape(arr, (2,3), 'C') #mas recomendado usar

array([[9, 6, 8],
       [2, 9, 8]])

In [39]:
np.reshape(arr, (2,3), 'F')

array([[9, 9, 2],
       [8, 6, 8]])

In [44]:
tensor = np.squeeze(tensor)
print(tensor, tensor.ndim)
tensor.shape


[[[   1    2    3    4]
  [  10   11   12   13]
  [  14   15   16   18]
  [  12   15   48    7]]

 [[  14   12   15   17]
  [  54   65   98   78]
  [   3    0   45   65]
  [   7    8    9   52]]

 [[  85   95   65   35]
  [  45   78   45 1200]
  [   0   12   36    5]
  [  45    8    7    6]]] 3


(3, 4, 4)

In [51]:
np.reshape(tensor, (3,2,8), 'C')

array([[[   1,    2,    3,    4,   10,   11,   12,   13],
        [  14,   15,   16,   18,   12,   15,   48,    7]],

       [[  14,   12,   15,   17,   54,   65,   98,   78],
        [   3,    0,   45,   65,    7,    8,    9,   52]],

       [[  85,   95,   65,   35,   45,   78,   45, 1200],
        [   0,   12,   36,    5,   45,    8,    7,    6]]])