# Main functions in numpy

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
arr

array([10, 16, 18, 10,  8, 12, 15,  4, 12,  3])

In [5]:
matrix = arr.reshape(2,5)
matrix

array([[10, 16, 18, 10,  8],
       [12, 15,  4, 12,  3]])

In [6]:
arr.max()

18

In [9]:
matrix.max(axis=0)  #0 columns and 1 rows

array([12, 16, 18, 12,  8])

In [11]:
arr.argmax()  #index where the max value is

2

In [13]:
matrix.argmax(1)

array([2, 1])

In [14]:
arr.min()
matrix.min(0)

array([10, 15,  4, 10,  3])

In [15]:
arr.argmin()
matrix.argmin(0)

array([0, 1, 1, 0, 1])

In [17]:
arr

array([10, 16, 18, 10,  8, 12, 15,  4, 12,  3])

In [16]:
arr.ptp() #distancia entre menos y mayor de datos

15

In [18]:
matrix

array([[10, 16, 18, 10,  8],
       [12, 15,  4, 12,  3]])

In [20]:
matrix.ptp(0)

array([ 2,  1, 14,  2,  5])

In [22]:
arr.sort()
arr

array([ 3,  4,  8, 10, 10, 12, 12, 15, 16, 18])

In [21]:
np.percentile(arr,50)

11.0

In [23]:
np.median(arr)

11.0

In [24]:
np.median(matrix,0)

array([ 7.5,  8. , 11.5, 13. , 14. ])

In [25]:
np.std(arr)

4.643274706497559

In [26]:
np.mean(arr)

10.8

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])


In [34]:
np.concatenate((a,b), axis =0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])