# Numpy and pandas


In [1]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8]
lista

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr.shape

(8,)

In [16]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)

#### Indexing

In [9]:
print(arr)
arr[0]

[1 2 3 4 5 6 7 8]


1

In [10]:
arr[0] + arr[5]

7

In [11]:
print(matriz)
matriz[0]   #imprime la fila 1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[1, 2, 3]

In [18]:
matriz[0,2]

3

#### Slicing

In [19]:
arr[0:3]  #me desde posicion 0 hasta 3-1

array([1, 2, 3])

In [20]:
arr[:3]  #arranca desde el primer elemento del array 

array([1, 2, 3])

In [22]:
arr[2:]  #arranca desde 0 hasta el final

array([3, 4, 5, 6, 7, 8])

In [23]:
arr[::3]  #me trae todos los elementos de 3 en 3

array([1, 4, 7])

In [25]:
arr[-1]

8

In [28]:
print(arr)
arr[-3:]

[1 2 3 4 5 6 7 8]


array([6, 7, 8])

In [29]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [32]:
matriz3d = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                    [[11,22,32], [14,25,78], [18,95,74]]])

In [33]:
matriz3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 32],
        [14, 25, 78],
        [18, 95, 74]]])

In [37]:
matriz3d[0,1,1]   #[matriz, fila, columna]

5

In [38]:
matriz3d[0,:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Numpy type of data

In [39]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [41]:
arr.dtype #see type of the the variable

dtype('int64')

In [43]:
arr = np.array([1,2,3,4], dtype = 'float64') #cambiar de int a float
arr.dtype

dtype('float64')

In [44]:
arr = arr.astype(np.float64)#otra forma de cambiar el formato